###Testing endpoints usig VsCode REST Client extension
@api = http://localhost:3000

### USER ENDPOINTS

GET {{api}}/api/users/

###
GET {{api}}/api/user/619bce3022772b30d0518336


### /register
POST {{api}}/api/register
Content-Type: application/json

{
  "firstname": "Rick",
  "lastname": "Sanchez",
  "email": "rick.sanchez@rickandmorty.com",
  "password": "12345678",
  "password2": "12345678",
  "role": "Admin"
}

### /login
POST {{api}}/api/login
Content-Type: application/json

{
  "email": "rick.sanchez@rickandmorty.com",
  "password": "12345678"
}

### /login
POST {{api}}/api/login
Content-Type: application/json

{
  "email": "robert.plant@attendance.com",
  "password": "12345678"
}

###
POST {{api}}/api/profile

###
POST {{api}}/api/logout


### ATTENDANCE ENDPOINTS

GET {{api}}/api/attendance/all

###
GET {{api}}/api/attendance/


### Add Attendance
POST {{api}}/api/attendance/create
Content-Type: application/json

{
  "author": "Rick Sanchez",
  "idAuthor": "618ad9eb7fc7da0cbcb6c75d",
  "subject": "Algebra: Vector and Matrix",
  "students": "25",
  "difficulties": "No internet connection"
}

### 