###Testing endpoints usig VsCode REST Client extension
@api = http://localhost:3000

### USER ENDPOINTS

GET {{api}}/api/users/

###
GET {{api}}/api/user/619bce3022772b30d0518336


### /register
POST {{api}}/api/register
Content-Type: application/json

{
  "firstname": "Rick",
  "lastname": "Sanchez",
  "email": "rick.sanchez@rickandmorty.com",
  "password": "12345678",
  "password2": "12345678",
  "role": "Admin"
}

### /login
POST {{api}}/api/login
Content-Type: application/json

{
  "email": "rick.sanchez@rickandmorty.com",
  "password": "12345678"
}

### /login
POST {{api}}/api/login
Content-Type: application/json

{
  "email": "robert.plant@attendance.com",
  "password": "12345678"
}

###
POST {{api}}/api/profile

###
POST {{api}}/api/logout


### ATTENDANCE ENDPOINTS

GET {{api}}/api/attendance/all

###
GET {{api}}/api/attendance/


### Add Attendance
POST {{api}}/api/attendance/create
Content-Type: application/json

{
  "author": "Robert Plant",
  "idAuthor": "619bcc81aba39633506b7acc",
  "subject": "English: Verb conjugation",
  "students": "34",
  "difficulties": "Holiday"
}

### PROGRAM ENDPOINTS

###
GET {{api}}/api/program/all

###
GET {{api}}/api/program/61b8f8a47ed7412710302ea0

###
POST {{api}}/api/program/create
Content-Type: application/json

{
  "code": "2711",
  "name": "Tecnologia es sistemas de información",
  "coordinator": "Ana Rey",
  "duration": "10"
}

### SUBJECT ENDPOINTS

###
GET {{api}}/api/subject/all

###
GET {{api}}/api/subject/61b8fa4a7ed7412710302ea1

###
POST {{api}}/api/subject/create
Content-Type: application/json

{
  "teacher": "Robert Plant",
  "name": "Técnicas de pruebas de software",
  "code": "750105M",
  "intensity": "4",
  "program": "2711"
}